### ISSUE TITLE
X_train reduced to one row after tsfel.time_series_features_extractor(cfg, X_train, fs=fs)

### ISSUE THREAD

**Issue by renzha-miun** [fraunhoferportugal/tsfel#86]
The X_train data reduced from 208 rows to just 1 row, resulting error for further execution of the code. What can go wrong? 

Here is the code:
```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(X_train)

cfg = tsfel.get_features_by_domain()
# Get features
X_train = tsfel.time_series_features_extractor(cfg, X_train, fs=fs)
X_test = tsfel.time_series_features_extractor(cfg, X_test, fs=fs)
print(X_train)
print(X_test)

corr_features = tsfel.correlated_features(X_train)
X_train.drop(corr_features, axis=1, inplace=True)
X_test.drop(corr_features, axis=1, inplace=True)
```

**Comment by dmfolgado** [comment]
Hi! Could you please confirm the type of X_train and X_test? Can you also confirm if you're interested in dividing `X_train` into windows? Consider also passing as: ```X_train = tsfel.time_series_features_extractor(cfg, [X_train], fs=fs)``` to see if the output is according to your requirements.

**Comment by renzha-miun** [comment]
I have tried but it did not work. Here is the error.

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/renzha/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/tefeltest.py", line 78, in <module>
    X_train = tsfel.time_series_features_extractor(cfg, X_train, fs=fs)
  File "/Users/renzha/PycharmProjects/pythonProject2/venv/lib/python3.8/site-packages/tsfel/feature_extraction/calc_features.py", line 294, in time_series_features_extractor
    pool = mp.Pool(cpu_count)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _fixup_main_from_path(data['init_main_from_path'])
    prepare(preparation_data)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    raise RuntimeError('''
    main_content = runpy.run_path(main_path,    
exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by dmfolgado** [comment]
I have looked into your traceback, and still, it is not completely clear what is causing the issue. I would need to replicate the issue. 
Can you share the data you're using?

The traceback suggests that it might be something related to multiprocessing. You can temporarily disable multiprocessing to check whether the error persists. To disable pass `n_jobs=1` as an argument in the `tsfel.time_series_features_extractor`.

**Comment by renzha-miun** [comment]
Thank you. You can find the input data here: https://github.com/renzha-miun/data-for-test/blob/main/df.txt.
The `n_jobs=1` did not work.

**Comment by dmfolgado** [comment]
I already took a look. The issue arises since you pass an unsupported data type. Since you have a multivariate time series dataset composed of 26 time series, you should pass a Dataframe with the 26 time series as columns (you're using as rows!). Take a look at our documentation [here](https://tsfel.readthedocs.io/en/latest/descriptions/get_started.html#extract-from-time-series-as-array-objects).

A quick workaround is to use the transpose. I recommend modifying the "signal" string by the name (unique identifier) of the time series:

```python
tsfel.time_series_features_extractor(cfg, df.T, fs=fs)
```

**Comment by renzha-miun** [comment]
It still does not work. I tried the original code from the documentation. However, the same error as I attached above appeared.
